import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/server";
import { sendNotification } from "@/server/notifications";
import { formatINR, paiseToRupees } from "@/lib/money";
import { publicEnv } from "@/lib/env";
import { createInvoice } from "@/server/services/invoices";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * Scheduler endpoint — run daily (Vercel Cron / n8n / GitHub Action):
 *   curl -X POST https://<app>/api/cron -H "Authorization: Bearer $CRON_SECRET"
 *
 * 1. Generates due recurring invoices (Automated Bills) and auto-shares them.
 * 2. Sends payment reminders per each tenant's reminder rules.
 * 3. Sends the owner's daily summary.
 *
 * See `vercel.json` for the schedule. Both GET and POST are supported: Vercel
 * Cron issues a GET, everything else here documents POST.
 */

type SnapshotLine = {
  item_id: string | null;
  name: string;
  hsn_sac: string | null;
  unit: string;
  qty: number;
  rate_paise: number;
  tax_rate: number;
};

/**
 * Numbering used to be done here with a read-then-update on the counter table,
 * justified by "cron runs single-threaded". That was only ever half true — a
 * UI or WhatsApp bill saved while cron was mid-run could still interleave and
 * duplicate a number. It now goes through the shared service, which uses the
 * atomic gst_next_invoice_number RPC. That RPC treats a NULL auth.uid() as a
 * trusted server caller, so cron works without an auth session.
 */

function advance(dateStr: string, frequency: string): string {
  const d = new Date(dateStr + "T00:00:00Z");
  if (frequency === "daily") d.setUTCDate(d.getUTCDate() + 1);
  else if (frequency === "weekly") d.setUTCDate(d.getUTCDate() + 7);
  else d.setUTCMonth(d.getUTCMonth() + 1);
  return d.toISOString().slice(0, 10);
}

export async function POST(req: NextRequest) {
  const secret = process.env.CRON_SECRET;
  const header = req.headers.get("authorization") ?? "";
  if (!secret || header !== `Bearer ${secret}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const admin = createAdminClient();
  const today = new Date().toISOString().slice(0, 10);
  const results = {
    invoicesCreated: 0,
    remindersSent: 0,
    ownerSummaries: 0,
    errors: [] as string[],
  };

  // ---- 1. Due recurring invoices ---------------------------------------------
  const { data: due } = await admin
    .from("aimunim_recurring_invoices")
    .select("*")
    .eq("is_active", true)
    .lte("next_run_date", today)
    .limit(200);

  for (const rec of due ?? []) {
    try {
      const [{ data: tenant }, { data: party }] = await Promise.all([
        // Existence check only — the invoice service resolves the tenant's
        // state/prefix and the party's place of supply itself.
        admin
          .from("aimunim_tenants")
          .select("id")
          .eq("id", rec.tenant_id)
          .single(),
        admin
          .from("aimunim_parties")
          .select("name, phone")
          .eq("id", rec.party_id)
          .single(),
      ]);
      if (!tenant || !party) throw new Error("Tenant/party missing");

      const lines = (rec.items as SnapshotLine[]) ?? [];
      if (!lines.length) throw new Error("No items in recurring bill");

      // Same invoice service the UI and the WhatsApp bill engine use, so a
      // recurring invoice is indistinguishable from a hand-entered one:
      // atomic numbering via gst_next_invoice_number, identical GST maths and
      // identical stock postings.
      const created = await createInvoice({
        db: admin,
        tenantId: rec.tenant_id,
        userId: null,
        source: "recurring",
        // The reminder text below is this job's own wording — don't let the
        // service send its generic copy as well.
        autoShare: false,
        input: {
          direction: "sale",
          voucherType: "invoice",
          invoiceType: "gst",
          partyId: rec.party_id,
          invoiceDate: today,
          additionalCharges: 0,
          roundOff: true,
          status: "final",
          template: "classic",
          notes: `Auto-generated by recurring bill "${rec.name}"`,
          lines: lines.map((l) => ({
            itemId: l.item_id,
            name: l.name,
            hsn_sac: l.hsn_sac ?? "",
            unit: l.unit,
            qty: l.qty,
            rate: paiseToRupees(l.rate_paise),
            taxRate: l.tax_rate,
            discountPercent: 0,
          })),
        },
      });
      if (created.error || !created.id || !created.invoiceNumber) {
        throw new Error(created.error ?? "Insert failed");
      }
      const number = created.invoiceNumber;
      const totalPaise = created.totalPaise ?? 0;

      await admin
        .from("aimunim_recurring_invoices")
        .update({
          next_run_date: advance(rec.next_run_date, rec.frequency),
          last_run_at: new Date().toISOString(),
        })
        .eq("id", rec.id);

      if (rec.auto_share && party.phone) {
        const pdfUrl = `${publicEnv.NEXT_PUBLIC_SITE_URL}/invoices/${created.id}/pdf`;
        await sendNotification({
          tenantId: rec.tenant_id,
          type: "invoice_generated",
          recipient: party.phone,
          body: `Dear ${party.name}, your invoice ${number} of ${formatINR(totalPaise)} has been generated. View: ${pdfUrl}`,
          params: { name: party.name, number, amount: (totalPaise / 100).toFixed(2), link: pdfUrl },
          entityType: "invoice",
          entityId: created.id,
        });
      }

      results.invoicesCreated += 1;
    } catch (e) {
      results.errors.push(`recurring ${rec.id}: ${e instanceof Error ? e.message : e}`);
    }
  }

  // ---- 2. Payment reminders per tenant rules ----------------------------------
  const { data: rules } = await admin
    .from("aimunim_reminder_rules")
    .select("*")
    .eq("enabled", true);

  for (const rule of rules ?? []) {
    try {
      // offset_days: -3 => remind 3 days BEFORE due; +7 => 7 days AFTER.
      const target = new Date();
      target.setUTCDate(target.getUTCDate() - rule.offset_days);
      const targetDate = target.toISOString().slice(0, 10);

      const { data: invoices } = await admin
        .from("aimunim_invoices")
        .select("id, invoice_number, party_id, total_paise, amount_paid_paise, due_date")
        .eq("tenant_id", rule.tenant_id)
        .eq("direction", "sale")
        .eq("voucher_type", "invoice")
        .eq("due_date", targetDate)
        .in("status", ["unpaid", "partial"]);

      for (const inv of invoices ?? []) {
        if (!inv.party_id) continue;
        const { data: party } = await admin
          .from("aimunim_parties")
          .select("name, phone")
          .eq("id", inv.party_id)
          .single();
        if (!party?.phone) continue;
        const duePaise = inv.total_paise - inv.amount_paid_paise;
        await sendNotification({
          tenantId: rule.tenant_id,
          type: "payment_reminder",
          recipient: party.phone,
          body: `Dear ${party.name}, invoice ${inv.invoice_number} of ${formatINR(duePaise)} is ${rule.offset_days >= 0 ? "overdue" : "due soon"} (due ${inv.due_date}). Kindly arrange the payment.`,
          params: { name: party.name, number: inv.invoice_number, amount: (duePaise / 100).toFixed(2) },
          entityType: "invoice",
          entityId: inv.id,
        });
        results.remindersSent += 1;
      }
    } catch (e) {
      results.errors.push(`rule ${rule.id}: ${e instanceof Error ? e.message : e}`);
    }
  }

  // ---- 3. Owner daily summary (tenants with the toggle on) ---------------------
  const { data: tenants } = await admin
    .from("aimunim_tenants")
    .select("id, name, phone, invoice_settings")
    .not("phone", "is", null);

  for (const t of tenants ?? []) {
    try {
      const settings = (t.invoice_settings ?? {}) as { owner_daily_summary?: boolean };
      if (!settings.owner_daily_summary || !t.phone) continue;

      const [{ data: invoices }, { data: payments }] = await Promise.all([
        admin
          .from("aimunim_invoices")
          .select("total_paise")
          .eq("tenant_id", t.id)
          .eq("direction", "sale")
          .eq("voucher_type", "invoice")
          .neq("status", "draft")
          .eq("invoice_date", today),
        admin
          .from("aimunim_payments")
          .select("amount_paise, mode, direction")
          .eq("tenant_id", t.id)
          .eq("payment_date", today),
      ]);

      const salesPaise = (invoices ?? []).reduce((s, i) => s + i.total_paise, 0);
      const inPaise = (payments ?? [])
        .filter((p) => p.direction === "in")
        .reduce((s, p) => s + p.amount_paise, 0);
      const cashPaise = (payments ?? [])
        .filter((p) => p.direction === "in" && p.mode === "cash")
        .reduce((s, p) => s + p.amount_paise, 0);
      const creditPaise = Math.max(0, salesPaise - inPaise);

      await sendNotification({
        tenantId: t.id,
        type: "order_status",
        recipient: t.phone,
        body: `${t.name} — aaj (${today}): Sales ${formatINR(salesPaise)} · ${(invoices ?? []).length} bills · Cash ${formatINR(cashPaise)} · Udhar ${formatINR(creditPaise)} · Total received ${formatINR(inPaise)}.`,
        template: "daily_summary",
        params: {
          date: today,
          sales: (salesPaise / 100).toFixed(2),
          bills: String((invoices ?? []).length),
          received: (inPaise / 100).toFixed(2),
        },
        entityType: "tenant",
        entityId: t.id,
      });
      results.ownerSummaries += 1;
    } catch (e) {
      results.errors.push(`summary ${t.id}: ${e instanceof Error ? e.message : e}`);
    }
  }

  return NextResponse.json({ ok: true, date: today, ...results });
}

/**
 * Vercel Cron invokes scheduled paths with a **GET**, not a POST — so without
 * this the job would 405 every night and Automated Bills would silently never
 * run. When CRON_SECRET is set in the project's env, Vercel sends it as
 * `Authorization: Bearer <CRON_SECRET>`, which is exactly the check POST
 * already performs, so the two are the same request in different clothes.
 */
export const GET = POST;
